### ISSUE TITLE
Typo on timeseries page

### ISSUE THREAD

**Issue by hadro** [pola-rs/polars-book#126]
Under the "Rolling Groupby" section, there's a typo in the year on the later bound of the values -- I believe it should be '2021', not '20210' in this sentence:

`So imagine having a time column with the values {2021-01-01, 20210-01-05} and a period="5d" this would create the following windows`

See: https://pola-rs.github.io/polars-book/user-guide/timeseries/intro.html#rolling-groupby

**Comment by ritchie46** [comment]
Thanks. This has been fixed now.
