### ISSUE TITLE
Python 3.8 quirk from reference guide hard-coding

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars-book#136]
## Problem

https://github.com/pola-rs/polars-book/blob/3610bb47000fd9d9fa783bd89d7c7d0a27fbb386/reference_guide_python/__main__.py#L19

This hard-coding makes using another Python version awkward. I'm also wondering if it's worth just bumping the Python version. I've been doing fine in the User Guide so far with 3.10.3.

## Solution

Dynamic path resolution/Python version flexibility. Upgrades in general.

**Comment by ritchie46** [comment]
This code can be removed, we don't use the astdocs anymore.

**Comment by cnpryer** [comment]
oo cool. I'll add this to my list.
