### ISSUE TITLE
Sentence ends mid-sentence

### ISSUE THREAD

**Issue by CaptainStabs** [pola-rs/polars-book#137]
https://pola-rs.github.io/polars-book/api-python/polars/internals/frame/DataFrame.html?highlight=dtype#polarsinternalsframedataframe
![image](https://user-images.githubusercontent.com/40151222/164779707-8f83810b-aa57-452a-bdcd-5d8284bcf265.png)

**Comment by cnpryer** [comment]
Hey @CaptainStabs your link 404s! Just a heads up.

**Comment by cnpryer** [comment]
Maybe this has already been resolved?

> Apply a horizontal reduction on a DataFrame. This can be used to effectively determine aggregations on a row level, and can be applied to any DataType that can be supercasted (casted to a similar parent type).

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.fold.html

**Comment by ritchie46** [comment]
Great! Thanks for the help. :)
