### ISSUE TITLE
User guide has some tiny errors

### ISSUE THREAD

**Issue by yanyu2015** [pola-rs/polars-book#141]
some tiny errors as follows:

![image](https://user-images.githubusercontent.com/11142054/167293023-3b6b4b60-5672-4109-9413-e2dadd4142b2.png)

![image](https://user-images.githubusercontent.com/11142054/167292996-de67d51c-7969-45a9-9ba8-6217fd97bd84.png)

you should specify which data you have used.
![image](https://user-images.githubusercontent.com/11142054/167293029-ade84aee-5a20-4917-8c45-f73cade976f6.png)

Is the user guide not completed？

**Comment by cnpryer** [comment]
I could probably check this out soon if no one else has gotten to it.

**Comment by cnpryer** [comment]
hey @yanyu2015! Could you point me in the right direction for this? 

1. I don't want to have to search around for the first example, so a link would be perfect.
2. Not sure I see what you'd like to change for the second snippet.
3. Manual Sum error should be fixed in #147

**Comment by yanyu2015** [comment]
1 It's pity that you are so lazy and  not familiar with your own cookbook
`[the link](https://pola-rs.github.io/polars-book/user-guide/dsl/contexts.html)`.
2 please give which specify data you use, it's ambiguous, are you sure that code can work well?

**Comment by ritchie46** [comment]
> It's pity that you are so lazy and not familiar with your own cookbook

It is not written by him. In any case it's a community efford. I would appreciate if you would stay respectful to our contributors they do this in their free time.

**Comment by yanyu2015** [comment]
I am sorry for my rude words. But I also do this in my free time, polars is great and I want to contribute to it.
I writed this issue TWICE before 14 days ago, but until today no one has fixed it or even knows where it is, which makes me feel uncomfortable. Cookbook is the most authoritative source for every beginner, and I think we should take it seriously. When I recommended polars to my friends, they felt that the cookbook was not friendly enough, which made me feel embarrassed.

**Comment by cnpryer** [comment]
Then let's improve it!

**Comment by cnpryer** [comment]
@yanyu2015 

> 1 It's pity that you are not familiar with your own cookbook. [the link](https://pola-rs.github.io/polars-book/user-guide/dsl/contexts.html).

Done!

> 2 please give which specify data you use, it's ambiguous, are you sure that code can work well?

Hmm.. curious. Maybe I'm looking at the wrong spot here as well, so correct me if I'm wrong, but there's a link to [US Congress dataset](https://github.com/unitedstates/congress-legislators) above the snippet. I see that it's not a link in your screenshot though.

**Comment by cnpryer** [comment]
Noticing there might be similar feedback from #120.

> Getting the US congress dataset code sample on GroupBy page (3.3) is very unclear about how to replicate ("from .dataset import dataset" doesn't work and is rather unclear how to execute other than that snippet)

**Comment by yanyu2015** [comment]
you are nice.
To the 2 point, the reason is the `from .dataset import dataset` seems not work. and [US Congress dataset](https://github.com/unitedstates/congress-legislators) is right, but there are so many datasets so taht people may not know which one is the right dataset the cookbook used. I try `legislators-current` and other dataset. If someone cannot replicate the result as the page presented they may feel confused.

**Comment by cnpryer** [comment]
Here's the `dataset` that's imported
https://github.com/pola-rs/polars-book/blob/b6e03837de0978932170a7d7ca763900b7fff08a/user_guide/src/examples/groupby_dsl/dataset.py#L1-L13

**Comment by yanyu2015** [comment]
I try the code again.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_35972/3485124543.py in <module>
      1 import polars as pl
      2 
----> 3 from .dataset import dataset
      4 
      5 q = (

ImportError: attempted relative import with no known parent package
```
I  see you have trid to fix it in #120

**Comment by cnpryer** [comment]
Try
```py
import polars as pl

url = "https://theunitedstates.io/congress-legislators/legislators-historical.csv"

dtypes = {
    "first_name": pl.Categorical,
    "gender": pl.Categorical,
    "type": pl.Categorical,
    "state": pl.Categorical,
    "party": pl.Categorical,
}

dataset = pl.read_csv(url, dtype=dtypes).with_column(
    pl.col("birthday").str.strptime(pl.Date, strict=False)
)

q = (
    dataset.lazy()
    .groupby("first_name")
    .agg(
        [
            pl.count(),
            pl.col("gender").list(),
            pl.first("last_name"),
        ]
    )
    .sort("count", reverse=True)
    .limit(5)
)

df = q.collect()
```

**Comment by yanyu2015** [comment]
ok, it works well. Let's close this issue.
