### ISSUE TITLE
Adding walk-through content, more documentation hand-holding, and examples completeness

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars-book#153]
This issue covers some of the feedback I have as a new (and currently limited) user of Polars. There's a lot to unpack for these proposals, so I'll start with some context for a foundation.

I'm a long time Pandas user who's worked on projects ranging from discovery work to implementing packaged compute pipelines in Python. I love what Pandas can do, but not how it's designed and often used. This is a major factor behind why I've grown interested in Polars and hope to get more involved to help polish and promote it as the viable DataFrame library it is.

## Motivation

Before listing my feedback I want to establish some core assumptions behind my perspective.

First I believe that (1) as an onboarding user the onus is on you to learn the library. (2) Sufficient documentation isn't *absolutely necessary* to learn Polars, but it will scale Polars' ability to onboard new users (in turn hopefully surrounding the project with more support), and thus should be prioritized within the context of documentation. (3) The API design is a primary *feature* of a DataFrame library and is a great selling point for a library like Polars. (4) Some people are thorough and will read through the documentation entirely, while others will look for quicker ways to get hands on. IME some people are just hands on and once you get them started it's easier to guide them through more details. It's really difficult to incentivize these users to read through the docs in their entirety without being more creative with the presentation/flow of the docs. FWIW I started out by reading through the entire user guide.

## Feedback

- **Introduction page is perfect**. I wouldn't change it.
- **Getting started feels short**. This is where I think the gap from motivation#4 can be filled. Getting Started content itself can and probably should be compact and to the point, but we can bridge into details and concepts more effectively from here
- For example *Expressions* could be a new concept to both Pandas and non-Pandas users. I'd guess that's a gigantic chunk of potential new users (if it's not the majority). Leading into expressions immediately may start some users off with more information overhead to digest than they *should* realize. This can be improved by **providing 5-10 minutes of opinionated walk-through style content** that covers an unspecific workflow using familiar DataFrame library behaviors (Create a dataframe, modify a dataframe, view data from a df, common operations on df, important and relevant data types for dfs, etc.)
- **User Guide needs more directional hand-holding to *educate* new users**. We can use links to redirect users to needed context/details for different topics that are covered. This leads into 2 major directions for documentation: (1) Topic introduction and (2) example completeness. Having actually been introduced to relatable DataFrame library behaviors, we can help users connect the dots between things like typical DataFrame usage behaviors and concepts like expressions, contexts, etc.
- I've been thinking a lot about example robustness and I'm struggling to see it as a net positive for the User Guide specifically. IMO the User Guide should focus on introducing users to Polars enough to get them moving and familiar enough to prevent anti-patterns or minimize user turnover. Otherwise you can end up with a pretty busy Cookbook. **Cookbooks shouldn't be too busy and should have clear objectives and *recipes* for visiting users** (another IMO). My feedback is that I'd expect example robustness to be an initiative for the Reference Guide. That doesn't mean it can't be augmented or supported in some form by the User Guide.
- At times I'd expect to find examples in the Reference Guide when I don't. This can be solved with the example completeness initiative.
- Maybe refining the Cookbook within the User Guide could help organize some of these changes. In other words making User Guide vs Cookbook more clear.

## Proposals

I'm putting this issue together to gauge interest. Please feel free to tear this apart.

- [ ] #154
- [ ] Add Fundamentals setup page
- [ ] Fill in some API docs gaps

### Improve *Getting Started* page by adding a guided walk-through

The walkthrough could be composed of the following:

1. Standards - Includes import, API philosophy, references.
2. Create data - Create a DataFrame, create a column/Series.
3. Modify data - Modify columns and values in a DataFrame.
4. View data - Selection of data from DataFrames with and without filters. Could include config references here.
5. General Ops - Merge, group, morph, etc.
6. Datetime behaviors and usage - Units, methods, etc.
7. Additional data types - Categoricals, struct, etc.
8. I/O - .csv, .parquet, SQL, why not Excel.

This gives the Cookbook a chance to provide surface-level explanations for certain decisions Polars makes through a relatable medium that includes pointers, recommendations, or just links to more relevant content. To me this is closer to actually *guiding users* through their onboarding rather than just giving them a topic-by-topic guide.

### Filling in API Reference gaps

- [Categorical examples](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.datatypes.Categorical.html?#polars.datatypes.Categorical)
- [Apply examples](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.apply.html)
- [StringCache examples](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.StringCache.html)

Edit: I'm getting this out to get this out. Reading this over I want to start with clearly defining directions for User Guide content, Cookbook content, and Reference content. I think that's the common denominator here.

**Comment by cnpryer** [comment]
Would love to self-assign this if possible.

**Comment by ritchie46** [comment]
> Would love to self-assign this if possible.

Please do. Can you make small PRs though. We don't have to do this at once.

**Comment by cnpryer** [comment]
Once I have more clarity on how I can approach this I'll simplify a lot of what I wrote in this issues description. 

> We don't have to do this at once.

For sure! I'd rather do it this way too.

The first PR will be just formalizing the improvements. Let me know what you think about the following (added before any walkthrough content).

![image](https://user-images.githubusercontent.com/14341145/171442359-455c3a23-97b5-40c2-ae16-d3f9ff8f70c7.png)

This assumes we just leave Cookbook == User Guide.

The PRs I'm planning so far would be something like:
1. Add table above + walkthrough content to Getting Started page
2. Add Fundamentals page after Getting Started to direct users if they haven't read the additional documentation they should
3. Add Guides page after Fundamentals page to post "Contributing" information to in order to standardize recipe contributions to the Cookbook
4. Distinguish between User Guide content, Cookbook recipes, and the API Reference (more organizational)
5. Fill in some API Reference gaps

Is that broken up enough?

**Comment by cnpryer** [comment]
hmm 

> I feel that the material in the 8 point list is too much for a quick start though

Yea so my thought process is that there's a quick start and there's a more robust walkthrough (if that's how we want to do this), but I don't see walkthrough == quickstart if that makes sense.

**Comment by cnpryer** [comment]
Getting back to this, I'm going to at least put together a draft starting the walk-through section. If we think it's too much we can just chop it down.

**Comment by cnpryer** [comment]
Opened #154 on the lighter side of possible walk-throughs. I still think something a bit more robust would be ideal and wouldn't sacrifice the message that readers shouldn't stop after the walkthrough.

For reference Pandas has a 10 minute guide. I noticed Explorer has one too.

**Comment by cnpryer** [comment]
closing for the updated #160
