### ISSUE TITLE
Update Python formatting for code snippets

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars-book#155]
## Problem
Looks like formatting is [a little unreadable](https://github.com/cnpryer/polars-book/blob/1e7f9fd40c66a0cb43c7f0d091c3721ed0de9dbc/user_guide/src/examples/dataframe/replace.py#L4) sometimes. 

## Solution
Update black line-length.

**Comment by ritchie46** [comment]
we need to add a traling comma after each argument. Black will then prefer multi-lines.

**Comment by cnpryer** [comment]
Makes sense, but what about aligning with PEP8? `--line-length=79` would produce

```py
df = df.with_column(
    pl.when(pl.col("rank") > 50)
    .then(pl.lit("red"))
    .otherwise(pl.col("color"))
    .alias("color")
)
```

**Comment by ritchie46** [comment]
The reason for the 120 chars whas that I found it a lot more readable for expressions. It lead to a single line per expression composition for most snippets, which is easy to mentally process.

That in combination with trailing commas, gives as a bit more control of how the formatting ends up.
