### ISSUE TITLE
missing comma in documentation

### ISSUE THREAD

**Issue by SnoozeFreddo** [pola-rs/polars-book#162]
Hi, 

just wanted to report a minor issue. 

https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html 

is missing a comma after col 'type'

df = pd.DataFrame({
    "type": ["m", "n", "o", "m", "m", "n", "n"]
    "c": [1, 1, 1, 2, 2, 2, 2],
})

**Comment by cnpryer** [comment]
Nice catch! You should submit a PR 😊

**Comment by cnpryer** [comment]
I can get this now if you want.

**Comment by cnpryer** [comment]
Btw @SnoozeFreddo you can add a code snippet by

\`\`\`python
doing this
\`\`\`

**Comment by cnpryer** [comment]
heh i keep doing that with `gh` cli. The merge targets my master. Let me fix.

**Comment by cnpryer** [comment]
Fixed :)

**Comment by SnoozeFreddo** [comment]
I just tried to make a pull request for another small issue in the docs text but i don't have the access rights to push. How can i make a pull request without permissions? @ritchie46 @braaannigan

There are also issues with the makefile

**Comment by braaannigan** [comment]
@SnoozeFreddo 
It's the standard procedure for these projects: 
- you fork the repo
- clone it to your machine
- make a branch
- make your changes
- make a PR and check that it passes ci
See the Contributing.md for more details or ping a message on discord if you get stuck
