### ISSUE TITLE
Resampling doc link is dead

### ISSUE THREAD

**Issue by SnoozeFreddo** [pola-rs/polars-book#164]
I am getting a 404 error when trying to access [the resampling page](https://pola-rs.github.io/polars-book/user-guide/timeseries/resampling.html).

Might be [this](https://github.com/pola-rs/polars-book/commit/ed2d25632c7e94c2e192061be97b0f130d6d49cc) commit but idk how the fix would look like.

**Comment by cnpryer** [comment]
I believe that's [here](https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/resampling.html) now

**Comment by cnpryer** [comment]
I think there was a lot of reorganization of content in a recent PR that probably broke those links. Definitely an opportunity for a PR :)

**Comment by cnpryer** [comment]
@SnoozeFreddo was the resampling link from the user guide? how/where did you spot that one?
