### ISSUE TITLE
Window function examples (ordering within group) seem to produce wrong results

### ISSUE THREAD

**Issue by SebAlbert** [pola-rs/polars-book#167]
Given the Pokemon dataset example, the code snippet
```
out = filtered.with_columns(
    [
        pl.col(["Name", "Speed"]).sort(reverse=True).over("Type 1"),
    ]
)
print(out)
```

apparently sorts Name and Speed individually. While not obviously meaningful (rows now combine names of Pokemon with speed values of different Pokemon, see for example the suggested "Speed of Slowbro" now being 15 instead of 30), this is probably still correct.

Furthermore, the last example should probably try to order descending or call the first 3 by "speed" the slowest 3 instead of the fastest 3.

I would like to (understand and) see the connection to usual 'window functions', and how to write things such as `lead` or `lag` known from SQL, as well as the explicit connection between SQL's `OVER (PARTITION BY x ORDER BY y)`, where the documentation currently only illustrates the `PARTITION BY x` part (and the API is calling it `over`), while the ordering remains unclear as of the seemingly meaningless results mentioned above.

**Comment by ritchie46** [comment]
Could be that I made non sensical examples. I will see if I can update them when I have a bit more time.

Regarding your questions, could you maybe make a SO question with some example data and your desired result, I am happy to answer it.

In general, the ordering of window functions is always with that group. So `sort` over `Type 1` sorts the elements within group `Type 1`

**Comment by cnpryer** [comment]
> Could be that I made non sensical examples. I will see if I can update them when I have a bit more time.

good first time issue label
