### ISSUE TITLE
missing_data.html link is dead

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars-book#177]
In Coming From Pandas [documentation](https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html), the [missing_data](https://pola-rs.github.io/polars-book/user-guide/missing_data.html) link is dead.

repost from https://github.com/pola-rs/polars/issues/4170

**Comment by mcrumiller** [comment]
To help whoever fixes this, the documentation's link points to https://pola-rs.github.io/polars-book/user-guide/missing_data.html, whereas it should point to https://pola-rs.github.io/polars-book/user-guide/howcani/missing_data.html.
