### ISSUE TITLE
Selecting with Expressions examples do not match associated sample code

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars-book#186]
See for e.g. here:

![image](https://user-images.githubusercontent.com/1896992/184990690-820d506f-e67c-49d0-baa1-2dc5eb0a2544.png)

In the first example, the assignment variable is wrong, as are in the input arguments to `df.select`:

```python
single_select_df = df.select(["id"]) # not list_select_df
print(single_select_df)
```
```text
shape: (3, 1)
┌─────┐
│ id  │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
└─────┘
```

In the second example, the assigned variable should be `list_select_df`.

In the section [Selecting Rows and Columns](https://pola-rs.github.io/polars-book/user-guide/howcani/selecting_data/selecting_data_expressions.html#selecting-rows-and-columns), the example only selects rows, not rows and columns.

**Comment by braaannigan** [comment]
This has been fixed, thanks @mcrumiller
