### ISSUE TITLE
Docs on how to programatically create a DataFrame

### ISSUE THREAD

**Issue by lfrancke** [pola-rs/polars-book#191]
A section on how to create a DataFrame in code (Rust) would be great.
There is some in the rustdocs on Series etc. but I believe a section in the book makes sense.
And neither rustdoc nor the book show an example of how to create a series/column of type `List`

**Comment by stinodego** [comment]
There's an example here:
https://pola-rs.github.io/polars-book/getting-started/series-dataframes/#dataframe
