### ISSUE TITLE
Documentation missing for required feature dtype-categorical for feature is_in

### ISSUE THREAD

**Issue by lfrancke** [pola-rs/polars-book#192]
When enabling "is_in" I get a compiler error unless I also add "dtype-categorical" and that's not documented anywhere I can see.

**Comment by braaannigan** [comment]
Hi @lfrancke - are feature gate requirements documented anywhere else?

**Comment by lfrancke** [comment]
I want to say "yes" but I can't find an example.
That said: I can't remember an instance of this either, maybe it's a bug instead?
If a feature A requires feature B, shouldn't A just add B automatically?

**Comment by ritchie46** [comment]
The combinations of features that compile are very hard to document. The maintenance burden and the combinatorial explosion is too high. You can open a PR in polars repo where you try to make it work without the `dtype-categorical` feature. 

To mitigate those issues we already run cargo hack where we try different features for compilation.
