### ISSUE TITLE
Documentation uses "col" without mentioning how to get the function

### ISSUE THREAD

**Issue by lfrancke** [pola-rs/polars-book#193]
The documentation nowhere mentions the feature flags needed to actually get started using polars. It jumps straight into using "col" which is not available.

One seems to at least need the "lazy" flag but I'm not sure.
The docs also switch between polars::prelude and polars_core::prelude which is also something that's never mentioned anywhere.

The Getting Started guide for example: https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html
It mentions cargo add polars and then jumps right into something called lazy polars without ever explaining what that is and it uses the col function as well. None of that works without enabling at least one feature.

**Comment by cchantep** [comment]
The rust examples seem quite outdated, which is really unfortunate as pola.rs looks greats.

**Comment by cchantep** [comment]
For now, none of the example is working. Quite critical.

**Comment by entwwwicklung** [comment]
are there any updates on this matter?

**Comment by c-peters** [comment]
Hi!

Thanks for raising the issue. Polars heavily relies on feature flags to turn on / off certain functionality to keep the compilation times down and avoid bloating the user with functionality which is not used. In  PR #307, I added the fact that you need the lazy feature flag for almost all examples in the installation pages. This should avoid new users running into the same issue. 

Additionally, for each of the current examples that require a different feature flag there is now a warning above the example notifying the user of this feature flag. 

We are still working on adding more examples for Rust & NodeJS. 


![Screenshot from 2023-05-03 15-48-46](https://user-images.githubusercontent.com/22658776/235936302-e0a8aa8c-a5d3-4919-9c77-39a839cd3405.png)
