### ISSUE TITLE
Add quickstart

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars-book#210]
I've written a quickstart notebook for Polars here:

https://colab.research.google.com/github/braaannigan/data-analysis-with-polars/blob/main/notebooks/intro/00-KeyConcepts.ipynb

We need a quickstart for the user guide as well - do you think this could be the basis of a quick start for the user guide? Obviously needs some tweaks for pep styling and removing references to the course

**Comment by braaannigan** [comment]
Any thoughts on this @ritchie46 @ghuls?

**Comment by ritchie46** [comment]
Yes, I think it could! Would be somewhat similar to the 10 minutes to pandas guide right? But then more expression oriented.

**Comment by braaannigan** [comment]
Closed by #216
