### ISSUE TITLE
example not reproducible 

### ISSUE THREAD

**Issue by JosiahParry** [pola-rs/polars-book#212]
This rust example does not work as is. 
Per the compiler I had to add `use std::io::Cursor;` to in order for the example to work
https://github.com/pola-rs/polars-book/blob/3278793c6129f9d1c16dc85f3ffedbd4852efd90/user_guide/src/quickstart/intro.md?plain=1#L73

**Comment by avimallu** [comment]
Shouldn't this be marked as resolved per #313?

**Comment by avimallu** [comment]
@c-peters, pinging you to aid in housekeeping, not to bug you. 😅

**Comment by JosiahParry** [comment]
@avimallu can you point me to this fix in the book? Perhaps I can verify independtly and close? :P

**Comment by avimallu** [comment]
I thought the linked pull request fixed it (someone re-linked this issue on there), #213. Is that not the case? 😅

**Comment by ritchie46** [comment]
Ping
