### ISSUE TITLE
Outdated link to Lazy API page from Multiprocessing page

### ISSUE THREAD

**Issue by gau-nernst** [pola-rs/polars-book#226]
https://github.com/pola-rs/polars-book/blob/fb169b2b3f44eb2a01fc33035e7c6f2ec4ec6561/user_guide/src/howcani/multiprocessing.md?plain=1#L17

On the live User Guide website, the [Multiprocess page](https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html), the link mentioned above is expanded to https://pola-rs.github.io/polars-book/user-guide/howcani/optimizations/lazy/intro.html. I believe `../` is missing to go up 1 directory level.

**Comment by braaannigan** [comment]
Thanks @gau-nernst, I'll include this in my next PR

**Comment by gau-nernst** [comment]
Polar docs is revamped. This issue is no longer valid.
