### ISSUE TITLE
groupby_dynamic example does the wrong thing

### ISSUE THREAD

**Issue by swpease** [pola-rs/polars-book#244]
The example [here](https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/temporal_groupby.html#using-expressions-in-groupby_dynamic) doesn't do what it says it should. Specifically, the `time` column is the same date repeated three times for each month, rather than the first three dates of each month.

Edit: I've been reading through more of the User Guide, so it looks like this works, but I don't know if it's the "good" way to do it:

```
from datetime import datetime
df = pl.date_range(low=datetime(2021, 1, 1), high=datetime(2021, 12, 31), interval="1d", name="time").to_frame()

out = (
    df.groupby_dynamic("time", every="1mo", period="1mo", closed="left")
    .agg(
        [
            pl.col("time").head(3).alias("day"),
            pl.col("time").cumcount().reverse().head(3).alias("day/eom"),
            ((pl.col("time") - pl.col("time").first()).last().dt.days() + 1).alias("days_in_month"),
        ]
    )
    .explode(["day", "day/eom"])
    .select(pl.exclude("time"))
)
print(out)
```

**Comment by braaannigan** [comment]
I see your point, we could do with an easier example

**Comment by stinodego** [comment]
The link in this issue doesn't work anymore. The related examples are now here:
https://pola-rs.github.io/polars-book/user-guide/transformations/time-series/rolling/

And it looks like they are fine. If not, please open a new issue in the main repo.
