### ISSUE TITLE
The read_csv not support glob

### ISSUE THREAD

**Issue by stalkerg** [pola-rs/polars-book#245]
Only `scan_csv` support patterns in the path. 
It should be fixed https://github.com/pola-rs/polars-book/blob/master/user_guide/src/examples/multiple_files/single_df.py

**Comment by braaannigan** [comment]
Thanks @stalkerg - I'm closing as this isn't seem to the case - I've just tested with some files to make sure.

Please reply if you think this is an error

**Comment by stalkerg** [comment]
in that case documentation was wrong, sorry
