### ISSUE TITLE
Missing curly bracket in example

### ISSUE THREAD

**Issue by extua** [pola-rs/polars-book#251]
I'm going through the Polars book and trying out the Rust examples, I'm familiar with Python but am just learning Rust so very much a beginner.

On [this page](https://pola-rs.github.io/polars-book/user-guide/dsl/expressions.html#expression-examples), the first Rust expression example to create a dataset throws an error:

```
error: this file contains an unclosed delimiter
  --> src/main.rs:17:2
   |
5  | fn main() -> Result<()> {
   |                         - unclosed delimiter
```

The main function is missing a closed bracket. I would do a pull request for [this file](https://github.com/pola-rs/polars-book/blob/master/user_guide/src/examples/expressions/expressions.rs) but see all the examples are in the one file so it might not be easy to resolve.

**Comment by mfloto** [comment]
This could be solved by placing the closing bracket at the end of the code block in the md file.
