### ISSUE TITLE
Optimisation section - lazy API

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars-book#253]
The optimisation section needs an overhaul. I propose to start with a review of the current lazy API section before adding anything new. 

We can add more on:
- combining multiple predicates
- slice pushdown
- CSE
- caching

Anything other thoughts @ritchie46 @r-brink?

**Comment by ritchie46** [comment]
Indeed. I think we can remove the examples shown (don't add much benefit IMO).

But what we do need is a table with all the optimizations and how often they run and what they do.

**Comment by r-brink** [comment]
YES! 🙌  We could create a new more coherent structure and rewrite + add some new content
