### ISSUE TITLE
Chapter on datatype casting

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars-book#263]
When reading the user guide I was missing information on how datatypes are cast.

For example: if I divide integer by integer, will I get integer or float? Can I control what I will get?

The book actually makes it look like that float * integer gets cast to integer and then back to float, which isn't true - but there are mistakes in the formatting that make it look like it does, because only 1 significant digit is shown:

See this part for example in the Python notebook section
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/25161793/221409790-3f95d353-bb2a-4114-a65e-3756d0ad6fb6.png">

The actual result is:

computed
-- |
f64
0.002688
0.004301
0.004839
0.004301
0.002688

I looked through the API docs for anything related to implicit casting but couldn't anything. Yes, there's an explicit casting function. But nothing about implicit casting, when doing something like `float * integer`. Rust would never allow you to do that without explicit casting. Polars seems to be doing implicit casting.

Would be good to add documentation on overloaded operators like `*`, `/` etc and how one can override implicit casting. What if I want integer division to stay with integers for example?

**Comment by stinodego** [comment]
There is a chapter on casting now:
https://pola-rs.github.io/polars-book/user-guide/expressions/casting/

If this is not sufficient, please open a new issue in the main repo.
