### ISSUE TITLE
Notebook output tables should show more significant figures and shows less precise datatypes

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars-book#264]
For some reason, the way you currently turn the notebook into markdown makes floats only have 2 significant figures, causing confusing results: instead of `31.5` the output gets rounded to `31`, which makes it look like an integer if one doesn't check the datatype row carefully:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/25161793/221411318-d0a4992c-f6bc-4138-92bd-b17da65bf96c.png">

When I execute the notebook with a more up to date nbconvert version, I get more significant figures - which is I think desirable:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/25161793/221411342-9bc4bcd4-d6fa-43be-97f1-80c2077b17df.png">

Also, I noticed that when I execute the notebook, `list` datatypes contain information about the inner values - which isn't the case in the currently live version.

What's currently online: `list`
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/25161793/221411439-b50c4dcf-1c81-4650-8754-76ca99cf986f.png">

What I get locally: `list[str]`
<img width="986" alt="image" src="https://user-images.githubusercontent.com/25161793/221411437-2d722102-d62f-4573-9d00-db91d83a385f.png">

Isn't it better to have the more precise datatypes?

https://github.com/pola-rs/polars-book/blob/3610bb47000fd9d9fa783bd89d7c7d0a27fbb386/user_guide/src/notebooks/introduction_polars.ipynb?short_path=3d0e98e#L1697-L1833

**Comment by braaannigan** [comment]
Thanks for the heads-up @corneliusroemer, these are now fixed in #290
