### ISSUE TITLE
Unclear/confusing comment: `# can be evaluated to 1 without programmer knowing`

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars-book#265]
In the Python notebook, there's a comment I find confusing: `# can be evaluated to 1 without programmer knowing`

What is this supposed to mean?

This is the full code snippet:

```py
# We can do arithmetic on columns and (literal) values
# can be evaluated to 1 without programmer knowing

some_var = 1

(df.select([
    ((pl.col("A") / 124.0 * pl.col("B")) / pl.sum("B") * some_var).alias("computed")
]))
```

The first part is clear "We can do arithmetic on columns and (literal) values" - but what is that "can be evaluated to 1 without programmer knowing" supposed to mean? Doesn't make much sense to me.

https://github.com/pola-rs/polars-book/blob/3610bb47000fd9d9fa783bd89d7c7d0a27fbb386/user_guide/src/notebooks/introduction_polars.ipynb?short_path=3d0e98e#L1539-L1542

**Comment by braaannigan** [comment]
Hi @corneliusroemer, I think a number of examples in this section were confusing and have been re-worked in #290. I think this particular example was also based on behaviour in a previous version and has been removed. Thanks for pointing this out!
