### ISSUE TITLE
fail to make

### ISSUE THREAD

**Issue by pea-sys** [pola-rs/polars-book#272]
The link in the Makefile directly under the repository is a dead link
https://github.com/pola-rs/polars-book/blob/master/Makefile
```
DATA_SRC=https://github.com/ritchie46/static/releases/download/0.0.1
DATA_SRC_STATIC=https://raw.githubusercontent.com/pola-rs/polars-static/master/data
```

**Comment by braaannigan** [comment]
Hi @pea-sys - do you mean https://raw.githubusercontent.com/pola-rs/polars-static/master/data? That link isn't supposed to work until the file paths are added further down. Or have I misunderstood?

**Comment by pea-sys** [comment]
@braaannigan 
Sorry.
I am wrong.
You are right.
I happened to be accessing the URL at a time when the network was off.
