### ISSUE TITLE
ENH: Improve linking from user guide to API reference

### ISSUE THREAD

**Issue by corneliusroemer** [pola-rs/polars-book#276]
It is useful to be able to quickly read the API reference when reading the user guide. Ideally, every type/function (basically anything generic in code fences) should be able to be linked to the API reference.

This is a bit of extra work but it really would help improve the usefulness of the guide. This would also in theory support showing inbounds links in the API guide as a "usage guide mentions" features. But that's not necessary for this to be useful.

As a start, this could be added to PR contribution guidelines/checklist `link to API reference`.

One challenge is how to deal with usage guide being sometimes language agnostic. So one may need to have multiple links, maybe like this:
> `pl.Duration` [[rs]](crates.io) [[py]](docs.polar.rs)
hough this would be noisy. Or alternatively:
> [`pl.Duration`](docs.polar.rs)[[rs]](crates.io)
where the default link could be Python.

One could also only use the more commonly used API (probably Python?) if the above is considered too noisy.

**Comment by c-peters** [comment]
Hi! 

The updated user guide should have this covered. In the tabbed code blocks there are links to the API documentation for each language separately.

**Comment by corneliusroemer** [comment]
Wow, the way this is implemented in the new guide is amazing. Well done! <3
