### ISSUE TITLE
include snippets not working

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars-book#277]
@braaannigan the include snippets in the new optimizations page doesn't seem to be loading.

https://pola-rs.github.io/polars-book/user-guide/lazy-api/lazy-query-plan.html

**Comment by ritchie46** [comment]
P.S. `join_asof` and `groupby_dynamic` are not supported streaming.

`explode, melt` are.

**Comment by braaannigan** [comment]
Changes applied in #291
