### ISSUE TITLE
'schema' parameter in polars.DataFrame.write_avro

### ISSUE THREAD

**Issue by kamilszym** [pola-rs/polars-book#283]
Hi,

I have to create avro file from my polars dataframe. However, i need a file with specific schema: a given name, write_avro also sets fields types to e.g a pair of (long, null), which I want to be just long. 

My solution to this problem is to convert dataset to pandas and then to dict (it's faster in pandas than in polars). Then, I create avro file with fastavro, where I can specify schema parameter. 

If it's possible, it would be really nice to be able to specify schema directly in write_avro method

**Comment by r-brink** [comment]
Hello @kamilszym, this repository is for the Polars book. It seems that your feature request is for the Polars library. You can open an issue here: https://github.com/pola-rs/polars

I will close this issue for now
