### ISSUE TITLE
DOC: Incorrect result display in `quick-exploration-guide`

### ISSUE THREAD

**Issue by luke396** [pola-rs/polars-book#296]
[Polars quick exploration guide - Polars - User Guide](https://pola-rs.github.io/polars-book/user-guide/quickstart/quick-exploration-guide.html)

<img width="624" alt="image" src="https://user-images.githubusercontent.com/77875500/232423259-648682b2-35bb-4ff5-8f40-ef4362c92b72.png">

The ideal output should be
```python
series = pl.Series("a", [1, 2, 3, 4, 5])
print(series)
# shape: (5,)
# Series: 'a' [i64]
# [
# 	1
# 	2
# 	3
# 	4
# 	5
# ]
```

**Comment by braaannigan** [comment]
Thanks @luke396, fixed in #295
