### ISSUE TITLE
Update read from S3, Azure blob etc

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars-book#298]
The docs for reading files from cloud storage are out-of-date. As there are a number of ways to do some of these operations I'd like to cover the range and note their pros/cons.

Anything else we should aim to cover here @ritchie46, @ghuls?

**Comment by alexander-beedie** [comment]
How to efficiently read multiple files from S3, such as partitioned parquet, is a common question. (I've been using `pl.scan_pyarrow_dataset` for that...)
