### ISSUE TITLE
Streaming page under construction in new docs

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars-book#304]
The streaming page is under construction for the new docs but was populated under the old docs:
https://pola-rs.github.io/polars-book/user-guide/lazy/streaming/

Any thoughts @c-peters?

**Comment by c-peters** [comment]
Hi!

For most features I split them up into 'concepts' and  examples / how to's. The first explains Polars as a library  allowing users to understand the library design a bit better, and the latter is more about doing by example.

For streaming I copied most of the content (except one example) to [concepts/streaming](https://pola-rs.github.io/polars-book/user-guide/concepts/streaming/), but still need to write some examples. 

Overall, I feel the streaming API deserves more attention then two subpages as it is a key feature for large datasets.
