### ISSUE TITLE
Make the difference between table operations and column operations more clear

### ISSUE THREAD

**Issue by CameronBieganek** [pola-rs/polars-book#318]
This is kind of a vague request, but I think the Polars book could spend a little time emphasizing the difference between table level operations like `df.filter()` and column expression level operations like `pl.col("x").filter()`.

See this issue for related discussion:
https://github.com/pola-rs/polars/issues/8680

**Comment by ritchie46** [comment]
We already have a small chapter on that: https://pola-rs.github.io/polars-book/user-guide/migration/spark/

And an intro on expressions https://pola-rs.github.io/polars-book/user-guide/concepts/expressions/.

Maybe you could make a proposal paragraph? I do think we can make the expression concepts a bit richer explaining the contexts and what expression represents in each. 

And maybe we could reiterate that they are "pure", have no side effects.

**Comment by CameronBieganek** [comment]
> We already have a small chapter on that: https://pola-rs.github.io/polars-book/user-guide/migration/spark/

Ah, I see. I had not read that chapter, because I was not coming from Spark. It's an important enough concept that it might be good to have similar content somewhere in the chapter on expressions. I might be able to write up a small proposal PR in the next week or so.
