### ISSUE TITLE
Return of the multi-processing page

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars-book#328]
Starting a new process on linux will fork the process, which is incredibly naive and has a high probability to leave any mutex in an invalid state.

Every project that does this: pytorch, joblib and others assume that none of the running processes do multi-threaded work and if one of them does, it can deadlock.

We have to explain this a lot and that gets tiring, so we set up a page for that.

See more context here: 

- https://github.com/pola-rs/polars/issues/5344
- https://github.com/pola-rs/polars/issues/8032
- https://github.com/pola-rs/polars/issues/3144

**Comment by taozuoqiao** [comment]
The multi-processing page is very helpful for new users of polars.

**Comment by ritchie46** [comment]
@c-peters can you take this one?
