### ISSUE TITLE
Struct Data Type

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars-book#329]
Hi!

Right now, the struct data type is not really covered. It is mentioned in the overview of [Data Types](https://pola-rs.github.io/polars-book/user-guide/concepts/data-types/).

- How to use the struct data type
- When to use the struct data type 
- What are the benefits / pitfalls

**Comment by ritchie46** [comment]
This is an important one as this one allows you to use multiple columns in the expression API.

**Comment by avimallu** [comment]
There is a touch-and-go mention of the struct data type in the [UDF](https://pola-rs.github.io/polars-book/user-guide/expressions/user-defined-functions/#combining-multiple-column-values) section of the book.

**Comment by cmdlineluser** [comment]
Hi there, I just noticed this repo.

I made an initial attempt at documenting Struct recently after a discussion in: https://github.com/pola-rs/polars/issues/7614

I've rewritten it in attempt to make it better, perhaps it could be of useful as a base for this if anybody wants to critique it: https://gist.github.com/cmdlineluser/175cdb7f22d575b7c5797c717b69f0f5

**Comment by c-peters** [comment]
Hi! @cmdlineluser, this could be a good start. Would you be willing to submit a PR?

**Comment by avimallu** [comment]
I can take a stab at this as well, building upon what @cmdlineluser linked.

**Comment by avimallu** [comment]
@mcrumiller, we do have a small section on using multiple columns in the [Polars book](https://pola-rs.github.io/polars-book/user-guide/expressions/user-defined-functions/#Combining-multiple-column-values).

I was thinking of taking a stab at it, and was debating whether having a full additional section on "custom functions on multiple columns" is necessary or whether we should just add on to what's already there.
