### ISSUE TITLE
List Data Type

### ISSUE THREAD

**Issue by c-peters** [pola-rs/polars-book#330]
Hi!

Right now, the list data type is not really covered. It is mentioned in the overview of [Data Types](https://pola-rs.github.io/polars-book/user-guide/concepts/data-types/).

- How to use the list data type
- When to use the list data type 
- What are the benefits / pitfalls
- Link to list expressions

**Comment by binu1515** [comment]
Either use pl.rows(named=True) or either use get_columns() method which would give you a list of Series, which you can then convert into a list of lists using the to_list() method on each Series in the list.

**Comment by avimallu** [comment]
Lists are covered very briefly in [Lists](https://pola-rs.github.io/polars-book/user-guide/expressions/lists/). Should the additional content for the book belong in this section, or a completely new section?

**Comment by avimallu** [comment]
@c-peters, I'll be taking a stab at this in the coming days, and wanted to ask if it's fine in the event the whole of https://pola-rs.github.io/polars-book/user-guide/expressions/lists/ gets removed to make a more cohesive introduction to lists?

@ritchie46, I plan to emphasize some content around how Polars `list`s are more simliar to Python `tuple`s, in the sense that all elements inside it must have the same datatype. Is that an accurate premise to move ahead with? I couldn't find much information on it in the API docs. I am going by this sentence in the doc:

> Luckily we have a data type that has the guarantee that the rows are homogeneous: pl.List data type.

**Comment by c-peters** [comment]
That is fine by me.

**Comment by ritchie46** [comment]
> @ritchie46, I plan to emphasize some content around how Polars lists are more simliar to Python tuples, in the sense that all elements inside it must have the same datatype. Is that an accurate premise to move ahead with? I couldn't find much information on it in the API docs. I am going by this sentence in the doc:

I don't think python tuple are the good example as they can have any mix of data types:

```python
(1, "foo")
```

This is in fact true for most languages that have tuples. I think that it is more akin to a `vector` type in many languages. It is important to stress that the data types in a `List` and `Array` are homogeneous. An `Array` is more similar to a numpy `ndarray`, whereas a `List` doesn't have a `shape` in a sense that all sublists can have a different length.

**Comment by avimallu** [comment]
> (1, "foo")

That was embarrassing. I wonder where I got that into my head. The comparison you mentioned makes much more sense; I never thought of comparing it to `vectors`.

Thank you for your input. I'll hopefully have something to review soon!
