### ISSUE TITLE
Add Python lambda example

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars-book#333]
Python lambda functions are mentioned here: https://pola-rs.github.io/polars-book/user-guide/expressions/aggregation/

Please add an example of how to use them with polars

**Comment by DeflateAwning** [comment]
After reading deeper into the book, I think the actual best solution is a link forward to this page (from the original place I mentioned is incomplete): https://pola-rs.github.io/polars-book/user-guide/expressions/user-defined-functions/

**Comment by c-peters** [comment]
Agreed!
