### ISSUE TITLE
Rust examples: `group_by` should be `groupby` ?

### ISSUE THREAD

**Issue by nabbisen** [pola-rs/polars-book#400]
I followed [the first Rust example](https://pola-rs.github.io/polars-book/#example) , and found it failed to run `cargo build` with Polars 0.32.1.

According to [the crate docs](https://docs.rs/polars/0.32.1/polars), the `fn` name which both [LazyFrame](https://docs.rs/polars/0.32.1/polars/prelude/struct.LazyFrame.html) and [DataFrame](https://docs.rs/polars/0.32.1/polars/frame/struct.DataFrame.html) have is **`groupby`**. I searched Rust examples in the book, and found several lines using **`group_by`**. Isn't it necessary to replace them with **`groupby`** as to Rust ?

---

My code which failed is:

```rust
use polars::prelude::*;

const DATA_SOURCE: &str = "my.csv";

fn main() {
    let q = LazyCsvReader::new(DATA_SOURCE)
        .has_header(true)
        .finish().unwrap()
        .filter(col("sepal_length").gt(lit(5)))
        .group_by(vec![col("species")])
        .agg([col("*").sum()]);
    
    let df = q.collect();
}
```

The error messages were:

```
error[E0599]: no method named `group_by` found for struct `LazyFrame` in the current scope
  --> src/main.rs:11:10
   |
7  |       let q = LazyCsvReader::new(DATA_SOURCE)
   |  _____________-
8  | |         .has_header(true)
9  | |         .finish()?
10 | |         .filter(col("sepal_length").gt(lit(5)))
11 | |         .group_by(vec![col("species")])
   | |         -^^^^^^^^ help: there is a method with a similar name: `groupby`
   | |_________|
   | 
```

**Comment by Atreyagaurav** [comment]
@stinodego I also noticed this and was thinking of telling you but forgot. You did mass replace of `groupby` to `group_by` and that affected the rust code as well. This isn't problematic for the new examples I added but the old ones probably have broken code.

**Comment by stinodego** [comment]
The Rust examples are indicative not of the latest Rust release, but of the main branch.

I will add a suitable warning to the docs once the move is complete.

**Comment by Atreyagaurav** [comment]
But isn't that confusing for people? Almost evey user that'll use polars in rust will use the latest version, not the latest commit. So in my opinion it'd make sense to keep the book example based on latest version and update them when you release a new version.

**Comment by stinodego** [comment]
It's not ideal, but there is no good solution until we synchronize the Python and Rust releases.

**Comment by stinodego** [comment]
See https://github.com/pola-rs/polars/issues/11102
