### ISSUE TITLE
Link to "10 minutes to Polars notebook" in howcani/intro.md is broken

### ISSUE THREAD

**Issue by davechallis** [pola-rs/polars-book#66]
In https://github.com/pola-rs/polars-book/blob/master/user_guide/src/howcani/intro.md

The link points to:
https://github.com/pola-rs/polars/blob/master/examples/python/10_minutes_to_polars.ipynb
which gives a 404.

**Comment by ritchie46** [comment]
Thanks for the heads up Dave!
