### ISSUE TITLE
Incorrect results in Polars expressions -> GroupBy -> Filtering

### ISSUE THREAD

**Issue by josham** [pola-rs/polars-book#88]
I was reading through this and noticed some incorrect results, see https://pola-rs.github.io/polars-book/user-guide/dsl/groupby.html#filtering.

- `avg M birthday` all > 2000
- `avg F birthday` all null

Also, given the `compute_age` calculation being used, the dataset should probably be using `legislators-current.csv"` rather than `legislators-historical.csv"`.

**Comment by cnpryer** [comment]
If this is still a thing I can snag it.
