### ISSUE TITLE
Code examples not displaying on some pages

### ISSUE THREAD

**Issue by simonw** [pola-rs/polars-book#90]
e.g. on https://pola-rs.github.io/polars-book/user-guide/dsl/intro.html#filter-and-conditionals

<img width="847" alt="Expressions_-_Polars_-_User_Guide" src="https://user-images.githubusercontent.com/9599/142139929-bae30180-79f5-4e4a-81be-e699481627ff.png">

**Comment by simonw** [comment]
Here's the problem:

https://github.com/pola-rs/polars-book/blob/841f86dcc0f7c338de5eb1b34efbc405922c74ef/user_guide/src/dsl/intro.md#L64-L72

That file looks like this:

https://github.com/pola-rs/polars-book/blob/841f86dcc0f7c338de5eb1b34efbc405922c74ef/user_guide/src/examples/expressions/expressions_examples_3.py#L1-L4

The `:5` at the end of `{{#include ../examples/expressions/expressions_examples_3.py:5:}} ` is cutting off the example.

**Comment by simonw** [comment]
Same problem affects https://pola-rs.github.io/polars-book/user-guide/dsl/contexts.html

**Comment by ritchie46** [comment]
Thanks! Fixed in #92

**Comment by ritchie46** [comment]
Oooooh... I see you beat me to it. :see_no_evil: Thanks again!
