### ISSUE TITLE
Expressions not showing in Contexts

### ISSUE THREAD

**Issue by dayalstrub-cma** [pola-rs/polars-book#94]
In a few of the contexts subsections, like [this one](https://pola-rs.github.io/polars-book/user-guide/dsl/contexts.html#select-in-eager-as-bracket-expressions) (and the ones below) the code snippet is not showing for me. 

I think the line number needs to be changed (to 4) here

https://github.com/pola-rs/polars-book/blob/a73a4c6bbe6c2ffee634b86b966551adcd5d2a6d/user_guide/src/dsl/contexts.md?plain=1#L34

and elsewhere, but can't run to check right now.

**Comment by ritchie46** [comment]
Thanks! This has been fixed now.
