### ISSUE TITLE
Wrong output in "How can I" examples?

### ISSUE THREAD

**Issue by dayalstrub-cma** [pola-rs/polars-book#95]
Unless I am mistaken, a few of the examples have output which instead looks like what the input should look like, e.g. [this one](https://pola-rs.github.io/polars-book/user-guide/howcani/df/common-manipulations.html#add-columns) is missing the new `"e"` column.

**Comment by ritchie46** [comment]
Ah, yes, I see you are right. Thanks for noting this.
